name: Versioning

on:
  push:
    branches:
      - fcpp-semver

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check build_type
        id: check_build_type
        run: |
          BUILD_TYPE=$(jq -r '.build_type' metadata.json)
          echo "build_type=$BUILD_TYPE" >> $GITHUB_OUTPUT
          if [ "$BUILD_TYPE" != "Release" ]; then
            echo "build_type is '$BUILD_TYPE', not 'Release'. Skipping versioning."
            exit 1
          fi
          echo "build_type is 'Release'. Continuing with versioning."

      - name: Set up Python
        if: steps.check_build_type.outcome == 'success'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Versioning Script
        if: steps.check_build_type.outcome == 'success'
        run: |
          chmod +x .github/misc/commit_semver.py
          python3 .github/misc/commit_semver.py

      - name: Push Changes
        if: steps.check_build_type.outcome == 'success'
        run: |
          git push origin fcpp-semver
